ideabin/urls.py
from django.urls import path
from . import views

from .views import IdeaListView, IdeaDetailView, IdeaCreateView, IdeaUpdateView, IdeaDeleteView

app_name='ideabin'

urlpatterns = [
    path('',IdeaListView.as_view(), name='index'),
    path('<int:pk>',IdeaDetailView.as_view(), name='detail'),
    path('add/',IdeaCreateView.as_view(), name='add'),
    path('edit/<int:pk>',IdeaUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>',IdeaDeleteView.as_view(), name='delete'),
]

journal/urls.py
from django.urls import path
from . import views
from .views import EntryDeleteView


app_name='journal'

urlpatterns = [
    path('',views.index, name='index'),
    path('add-new/',views.add, name='add'),
    path('transact/<int:pk>',views.create, name='create'),
    path('store/<int:pk>',views.store, name='store'),
    path('edit/<int:id>',views.edit, name='edit'),
    path('delete/<int:pk>',EntryDeleteView.as_view(), name='delete'),
]

wealthy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journal.urls')),
    path('accounts/', include('accounts.urls')),
    path('ideabin/', include('ideabin.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),  # <--

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Entry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="entries")
    title = models.CharField(blank=True, null=True, max_length=255)
    body = models.TextField(blank=True, null=True)
    entry_date = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'entries'
        ordering = ['-updated_at']


    def __str__(self):
        return self.title

journal/forms.py
from django.forms import ModelForm
from .models import Entry

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = ['title','body']

journal/views.py
from django.shortcuts import render, redirect
from .forms import EntryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import DeleteView
from django.urls import reverse_lazy
from django.utils import timezone
import json

from django.http import HttpResponse, JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from . models import Entry
# Create your views here.

@login_required
def index(request):
    entries_list = request.user.entries.all()
    paginator = Paginator(entries_list, 10)
    page = request.GET.get('page')
    entries = paginator.get_page(page)

    return render(request, 'journal/index.html', { "entries" : entries })


# Never call this except from the Add New Entry Button
@login_required
def add(request):
    
    entry = Entry.objects.create(user=request.user)

    return redirect('journal:create', pk=entry.pk)

# A Pseudo redirect for creation page, can handle straight traffic too
@login_required
def create(request, pk):
    if request.method == 'GET':
        entry = Entry.objects.get(pk=pk)
        form = EntryForm(instance=entry)
        return render(request, 'journal/add.html', { "entry" : entry, "form" : form })
    else:
        # let's just save the body and title content
        data = request.POST

        entry = Entry.objects.get(pk=pk)
        entry.body = data['body']
        entry.title = data['title']
        entry.save()

        return JsonResponse({ "message" : "Success!" })
    

# When the user submits, this should handle it
@login_required
def store(request, pk):
    entry = Entry.objects.get(pk=pk)

    form = EntryForm(request.POST, instance=entry)

    if form.is_valid():
        entry = form.save(commit=False)
        entry.save()

        return redirect('journal:index')

@login_required
def edit(request, id):
    entry = request.user.entries.get(pk=id)

    if request.method == "POST":
        form = EntryForm(request.POST, instance=entry)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = request.user
            entry.entry_date = timezone.now()
            entry.save()

            return redirect('journal:index')
    else:
        form = EntryForm(instance=entry)
        return render(request, 'journal/edit.html', { "entry" : entry, "form" : form })


class EntryDeleteView(LoginRequiredMixin, DeleteView):
    model = Entry
    success_url = reverse_lazy("journal:index")

journal/templates/journal/add.html
{% extends "household/master_argon.html" %}
{% load crispy_forms_tags %}

{% block title %}
Add New Entry
{% endblock title %}

{% block content %}

<div class="container-fluid p-3">

    <!-- <div class="ui segment">
        <div class="ui breadcrumb">
            <a class="section" href="{% url 'journal:index' %}">Home</a>
        </div>
    </div> -->

    <div class="card">
        <div class="card-header">
            <h3>Add/Edit Journal Entry</h3>
        </div>    
        <div class="card-body">
            <form action="{% url 'journal:store' pk=entry.pk %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success">
                    Done
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js"></script>
<script>
    $(document).ready(function () {

        var title = $('#id_title').val();

        $('#id_title').on('change', function(e) {
            title = $(this).val();
        });

        tinymce.init({
            selector: '#id_body',
            toolbar: [
            'bold italic underline blockquote fontsizeselect | list | alignleft aligncenter alignright | numlist bullist | table codesample forecolor backcolor emoticons | fullscreen',
            ],
            plugins: ["lists","fullscreen","codesample","textcolor colorpicker","emoticons","advlist", "table", ],
            menubar: false,
            statusbar: false,
            browser_spellcheck: true,
            branding: false,
            height: '70vh',
            placeholder: 'Compose an Epic ...',
            init_instance_callback: function(editor) {
                editor.on('keydown', _.debounce(function(e) {
                    // let's write an AJAX call to this here.

                    $('.ui.green.button').toggleClass('loading');

                    $.ajax({
                        method: 'POST',
                        data: {
                            'csrfmiddlewaretoken' : $('input[name="csrfmiddlewaretoken"]').val(),
                            'body': editor.getContent(),
                            'title': title
                        },
                        success: function(res) {
                            console.log(res.data)
                            $('.ui.green.button').toggleClass('loading')
                        }
                    })
                    // console.log(e.target)
                }, 300))
            }
        });
    })
</script>

{% endblock scripts %}

journal/templates/journal/edit.html
{% extends "household/master.html" %}

{% block content %}
  
<div class="ui container" style="margin-top: 75px;">

    <div class="ui segment">
        <div class="ui breadcrumb">
            <a class="section" href="{% url 'journal:index' %}">Home</a>
        </div>
    </div>

    <div class="ui segment">
        <h3>Edit Entry - {{ entry.title }}</h3>
        <hr class="ui divider">

        <form action="{% url 'journal:edit' entry.id %}" class="ui form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="ui button blue">
                Update
            </button>
        </form>

    </div>
</div>

{% endblock content %}

{% block scripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
<script>
    $(document).ready(function() {
        tinymce.init({
            selector: '#id_body',
            plugins: "lists",
            toolbar: [ 
            'bold italic underline | list | alignleft aligncenter alignright | numlist bullist',
            ],
            menubar: false
        });
    })
</script>

{% endblock scripts %}

journal/templates/journal/entry_confirm_delete.html
{% extends 'household/master.html' %}

{% block title %}
Confirm Delete
{% endblock title %}

{% block content %}

<div class="ui container" style="margin-top: 75px;">
    <div class="ui segment">
        <h1>Confirm Delete Entry : {{ entry.title }}</h1>
    
    
        <form method="post">
            {% csrf_token %}
    
            <button class="ui red button">
                Delete
            </button>
    
            <a href="{% url 'journal:index' %}" class="ui button blue">
                Cancel
            </a>
        </form>      
    </div>
</div>

{% endblock content %}

journal/templates/journal/index.html
{% extends "household/master_argon.html" %}

{% load humanize %}

{% block title %}Journal - All Entries{% endblock %}

{% block content %}

<div class="container">
        <div class="mt-5">

            <h1>
                My Journal Entries
            </h1>

            <hr>

            <p>
                <a href="{% url 'journal:add' %}" class="btn btn-success">
                    Add New Entry
                </a>
            </p>

            <div class="table-responsive">
                <table class="table table-bordered text-center">
                    <thead class="table-dark">
                        <tr>
                            <th>Title</th>
                            <th>Entry Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in entries %}
                        <tr>
                            <td>{{ entry.title }}</td>
                            <td>{{ entry.entry_date|naturaltime }}</td>
                            <td>
                                <div class="row">
                                    <div class="col" style="margin-bottom: 1em;">
                                        <a class="btn btn-success" tabindex="0" href="{% url 'journal:create' entry.id %}">
                                            Edit Idea
                                        </a>
                                    </div>
                                    <div class="col">
                                        <a class="btn btn-danger" tabindex="0" href="{% url 'journal:delete' pk=entry.id %}">
                                            Delete Entry
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


                <nav>
                    <ul class="pagination">
                        {% for i in entries.paginator.page_range %}
                            {% if entries.number == i %}
                            <li class="page-item active">
                                <a href="?page={{ i }}" class="page-link">
                                    {{ i }}
                                </a>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a href="?page={{ i }}" class="page-link">
                                    {{ i }}
                                </a>
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </nav>

            </div>
        </div>
    </div>

{% endblock content %}