ideabin/urls.py
from django.urls import path
from . import views

from .views import IdeaListView, IdeaDetailView, IdeaCreateView, IdeaUpdateView, IdeaDeleteView

app_name='ideabin'

urlpatterns = [
    path('',IdeaListView.as_view(), name='index'),
    path('<int:pk>',IdeaDetailView.as_view(), name='detail'),
    path('add/',IdeaCreateView.as_view(), name='add'),
    path('edit/<int:pk>',IdeaUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>',IdeaDeleteView.as_view(), name='delete'),
]

wealthy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journal.urls')),
    path('accounts/', include('accounts.urls')),
    path('ideabin/', include('ideabin.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),  # <--

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideabin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Idea(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ideas')
    title = models.CharField(blank=True, null=True, max_length=255)
    body = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='ideabin_images', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'ideas'
        ordering = ['-updated_at']
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("ideabin:detail", kwargs={'pk' : self.pk})
        

ideabin/forms.py
from django.forms import ModelForm
from .models import Idea

class IdeaForm(ModelForm):
    class Meta:
        model = Idea
        fields = ['title','body']

ideabin/views.py
from django.shortcuts import render, redirect
from . models import *
from .forms import IdeaForm

from django.urls import reverse, reverse_lazy

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import (View, 
                                  ListView, 
                                  TemplateView, 
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
# Create your views here.
class IdeaListView(LoginRequiredMixin,ListView):
    model = Idea
    context_object_name = 'ideas'
    template_name = 'ideabin/index.html'

class IdeaDetailView(LoginRequiredMixin,DetailView):
    model = Idea
    context_object_name = 'idea_detail'
    template_name = 'ideabin/idea_detail.html'

class IdeaCreateView(LoginRequiredMixin,CreateView):
    model = Idea
    fields = ('title','body','image')
    template_name = 'ideabin/add.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user.id
        self.object.save()

        return super(IdeaCreateView, self).form_valid(form)
    

class IdeaUpdateView(LoginRequiredMixin,UpdateView):
    model = Idea
    fields = ('title','body','image')
    template_name = 'ideabin/edit.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = self.request.user.id
        self.object.save()

        return super(IdeaUpdateView, self).form_valid(form)


class IdeaDeleteView(LoginRequiredMixin,DeleteView):
    model = Idea
    success_url = reverse_lazy("ideabin:index")

ideabin/templates/ideabin/add.html
{% extends "household/master_argon.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid p-3">

    <div class="ui segment">
        <h1>
            {% if not form.instance.pk %}
                Add New Idea
            {% else %}
                Update Idea
            {% endif %}
        </h1>
    
        <form class="ui form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success">
                Submit
            </button>
        </form>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
<script>
    $(document).ready(function () {
        tinymce.init({
            selector: '#id_body',
            toolbar: [
            'bold italic underline blockquote fontsizeselect | list | alignleft aligncenter alignright | numlist bullist | table codesample forecolor backcolor emoticons | fullscreen',
            ],
            plugins: ["lists","fullscreen","codesample","textcolor colorpicker","emoticons","advlist", "table", ],
            menubar: false,
            statusbar: false,
            browser_spellcheck: true,
            branding: false,
            height: '70vh',
            placeholder: 'Compose an Epic ...',
        });
    })
</script>

{% endblock scripts %}

ideabin/templates/ideabin/edit.html
{% extends "household/master_argon.html" %}

{% load crispy_forms_tags %}

{% block content %}
  
<div class="container-fluid p-3">
    <div class="card">
        <div class="card-header">
            <h3>Edit Idea - {{ idea.title }}</h3>
        </div>
        <div class="card-body">
            <form class="ui form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary">
                    Update
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
<script>
    $(document).ready(function() {
        tinymce.init({
            selector: '#id_body',
            toolbar: [
            'bold italic underline blockquote fontsizeselect | list | alignleft aligncenter alignright | numlist bullist | table codesample forecolor backcolor emoticons | fullscreen',
            ],
            plugins: ["lists","fullscreen","codesample","textcolor colorpicker","emoticons","advlist", "table", ],
            menubar: false,
            statusbar: false,
            browser_spellcheck: true,
            branding: false,
            height: '70vh',
            placeholder: 'Compose an Epic ...',
        });
    })
</script>

{% endblock scripts %}

ideabin/templates/ideabin/idea_confirm_delete.html
{% extends 'household/master.html' %}

{% block title %}
Confirm Delete
{% endblock title %}

{% block content %}

<div class="ui container" style="margin-top: 75px;">
    <div class="ui segment">
        <h1>Confirm Delete Idea : {{ idea.title }}</h1>
        
        <form method="post">
            {% csrf_token %}
    
            <button class="ui red button">
                Delete
            </button>
    
            <a href="{% url 'ideabin:detail' pk=idea.pk %}" class="ui button blue">
                Cancel
            </a>
        </form>      
    </div>
</div>


{% endblock content %}

ideabin/templates/ideabin/idea_detail.html
{% extends 'household/master_argon.html' %}

{% load static %}

{% block title %}
Showing Idea
{% endblock title %}

{% block content %}

<div class="ui container" style="margin-top: 75px;">

    <div class="row">
        <div class="col-sm-12 col-md-8 offset-md-2">
            <div class="card">
                {% if idea_detail.image %}
                    <img src="{{ idea_detail.image.url }}" alt="{{ idea_detail.title }}" class="card-img-top">
                {% endif %}
                <div class="card-body">
                    <h2 class="card-title">
                        {{ idea_detail.title }}
                    </h2>
                    {% autoescape off %}
                    {{ idea_detail.body }}
                    {% endautoescape %}
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5 text-center">
        <div class="col-6">
            <a class="btn btn-primary" href="{% url 'ideabin:edit' pk=idea_detail.pk %}">
                Edit Idea
            </a>
        </div>
        <div class="col-6">
            <a class="btn btn-danger" href="{% url 'ideabin:delete' pk=idea_detail.pk %}">
                Delete Idea
            </a>
        </div>
    </div>

</div>

{% endblock content %}

ideabin/templates/ideabin/idea_list.html
{% extends "household/master.html" %}

{% block title %}
Ideabin 
{% endblock title %}

{% block content %}

<div class="ui container">
    <div class="ui segment">
        <h3>Listing All Ideas - using Django's Generic ListView</h3>

        <table class="ui celled padded blue table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Idea Title</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for idea in idea_list %}
                <tr>
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        {{ idea.title }}
                    </td>
                    <td>
                        {{ idea.created_at | date }}
                    </td>
                    <td>
                        <a href="#">
                            Edit
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

ideabin/templates/ideabin/index.html
{% extends "household/master_argon.html" %}

{% block title %}
Ideabin 
{% endblock title %}

{% block content %}

<div class="container mt-5">
    <div>
        <h1 class="ui centered header">
            <i class="ni ni-atom"></i>
            Listing All Ideas
        </h1>

        <p>
            <a class="btn btn-success btn-icon" tabindex="0" href="{% url 'ideabin:add' %}">
                <span class="btn-inner--icon">
                    <i class="fa fa-plus"></i>
                </span>    
                <span class="btn-inner--text">
                    Add New Idea
                </span>
            </a>
        </p>

        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Idea Title</th>
                        <th>Created At</th>
                        <th>Last Updated On</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for idea in ideas %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>
                            <a href="{{ idea.id }}">
                                {{ idea.title }}
                            </a>
                        </td>
                        <td>
                            {{ idea.created_at }}
                        </td>
                        <td>
                            {{ idea.updated_at }}
                        </td>
                        <td>
                            <div class="row text-center">
                                <div class="col mb-1">
                                    <a class="btn btn-primary btn-icon" tabindex="0" href="{% url 'ideabin:edit' pk=idea.pk %}">
                                        <span class="btn-inner--icon">
                                            <i class="fa fa-edit"></i>
                                        </span>
                                        <span class="btn-inner--text">
                                            Edit Idea
                                        </span>
                                    </a>
                                </div>

                                <div class="col">
                                    <a class="btn btn-danger btn-icon" tabindex="0" href="{% url 'ideabin:delete' pk=idea.pk %}">
                                        <span class="btn-inner--icon">
                                            <i class="fa fa-trash"></i>
                                        </span>
                                        <span class="btn-inner--text">
                                            Delete Idea
                                        </span>
                                    </a>
                                </div>
                                <!-- /.col -->
                            </div>
                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}