accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('settings/',views.settings,name='settings'),
    path('set_password/',views.set_password,name='set_password'),
]

ideabin/urls.py
from django.urls import path
from . import views

from .views import IdeaListView, IdeaDetailView, IdeaCreateView, IdeaUpdateView, IdeaDeleteView

app_name='ideabin'

urlpatterns = [
    path('',IdeaListView.as_view(), name='index'),
    path('<int:pk>',IdeaDetailView.as_view(), name='detail'),
    path('add/',IdeaCreateView.as_view(), name='add'),
    path('edit/<int:pk>',IdeaUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>',IdeaDeleteView.as_view(), name='delete'),
]

journal/urls.py
from django.urls import path
from . import views
from .views import EntryDeleteView


app_name='journal'

urlpatterns = [
    path('',views.index, name='index'),
    path('add-new/',views.add, name='add'),
    path('transact/<int:pk>',views.create, name='create'),
    path('store/<int:pk>',views.store, name='store'),
    path('edit/<int:id>',views.edit, name='edit'),
    path('delete/<int:pk>',EntryDeleteView.as_view(), name='delete'),
]

wealthy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journal.urls')),
    path('accounts/', include('accounts.urls')),
    path('ideabin/', include('ideabin.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),  # <--

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/household/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to Wealthy - {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="site-wrapper">

    <header>
        <div class="ui top fixed inverted menu">
            <a href="{% url 'journal:index' %}" class="item">
                Journal
            </a>
            <a href="{% url 'ideabin:index' %}" class="item">
                IdeaBin
            </a>
        
            <div class="right menu">
                {% if request.user.is_authenticated %}
                <div class="ui dropdown item">
                    <i class="icon user"></i>
        
                    <div class="menu">
                        <a href="{% url 'accounts:settings' %}" class="item">Profile Settings</a>
                        <a href="{% url 'accounts:logout' %}" class="item">Logout</a>
                    </div>
                </div>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="item">
                    Login
                </a>
                {% endif %}
            </div>
        </div>
    </header>


    <div class="ui container fluid site-content">    
        {% block content %}
        {% endblock content %}
    </div>


    <footer>
        <!-- <p>This is a Footer</p> -->
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.js"></script>
    <script>
        $(document).ready(function() {
            $('.ui.dropdown').dropdown();
        })
    </script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/household/master_argon.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="{% static 'vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link type="text/css" href="{% static 'css/argon.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Wealthy - {% block title %}{% endblock %}</title>
</head>
<body class="site-wrapper">

    {% if 'login' not in request.path %}
    <header>
        {% include 'household/navigation_argon.html' %}
    </header>
    {% endif %}

    <main class="site-content mb-5">
        {% block content %}
        {% endblock content %}
    </main>

    {% if 'login' not in request.path %}
    <footer class="footer">
        <div class="container">
            <p class="text-center">
                Made with <i class="fa fa-heart" style="color: #ff1744"></i> for Django & Coffee.
            </p>
            <p class="text-center">
                Thank you Tim for <a href="https://creative-tim.com">Argon Design System.</a>
            </p>
        </div>
    </footer>
    {% endif %}
    <!-- Core -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>

    <!-- Theme JS -->
    <script src="{% static 'js/argon.min.js' %}"></script>

    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/household/navigation_argon.html
<nav class="navbar navbar-expand-lg navbar-dark bg-default">
    <div class="container">
        <a class="navbar-brand" href="/">
            Wealthy
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-default" aria-controls="navbar-default"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-default">
            <div class="navbar-collapse-header">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{% url 'journal:index' %}">
                            Wealthy
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-default" aria-controls="navbar-default"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>

            <ul class="navbar-nav ml-lg-auto">
                <li class="nav-item">
                    <a class="nav-link nav-link-icon" href="{% url 'journal:index' %}" title="Journal">
                        <i class="ni ni-paper-diploma"></i>
                        <span class="nav-link-inner--text d-lg-none">Journal</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-icon" href="{% url 'ideabin:index' %}" title="IdeaBin">
                        <i class="ni ni-atom"></i>
                        <span class="nav-link-inner--text d-lg-none">IdeaBin</span>
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link nav-link-icon" href="#" id="navbar-default_dropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <i class="ni ni-settings-gear-65"></i>
                        <span class="nav-link-inner--text d-lg-none">Settings</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
                        <a class="dropdown-item" href="{% url 'accounts:settings' %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>